### ISSUE TITLE
有PDF版本吗

### ISSUE THREAD

**Issue by ghost** [dairongpeng/algorithm-note#3]
有PDF版本吗

**Comment by dairongpeng** [comment]
文档都是通过有道云笔记记录的，你可以clone下来，用有道云打开，相关图形就显示出来了。或者你找个在线md转pdf的自己转一下

**Comment by dairongpeng** [comment]
github对md的图形的支持还是不太行，我有时间也会再优化一下的

**Comment by ghost** [comment]
okay. Thanks.
